/**
 * 대한민국 제22대 국회의원 현역 명부 데이터셋
 *
 * 기준일: 2026-06-05 국회 변동표 기준
 * 출처:
 * - 지역구 기본 당선자: 위키백과 지역별 제22대 국회의원 선거 결과표
 * - 비례대표 기본 당선자: 위키백과 제22대 국회의원 선거 비례대표 결과표
 * - 의원직 상실, 사퇴, 비례 승계, 재보궐, 당적 변동: 위키백과 제22대 대한민국 국회 변동표
 *
 * 주의: 전과 데이터는 이 파일에서 임의 생성하지 않습니다.
 * 선관위 후보자 공시자료와 별도 대조가 끝난 항목만 crimes에 채워야 합니다.
 */

const assemblyMembers = [
  {
    "name": "권성동",
    "party": "국민의힘",
    "constituency": "강원 강릉시",
    "is_proportional": false,
    "id": 1,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이철규",
    "party": "국민의힘",
    "constituency": "강원 동해시·태백시·삼척시·정선군",
    "is_proportional": false,
    "id": 2,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이양수",
    "party": "국민의힘",
    "constituency": "강원 속초시·인제군·고성군·양양군",
    "is_proportional": false,
    "id": 3,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박정하",
    "party": "국민의힘",
    "constituency": "강원 원주시 갑",
    "is_proportional": false,
    "id": 4,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "송기헌",
    "party": "더불어민주당",
    "constituency": "강원 원주시 을",
    "is_proportional": false,
    "id": 5,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "허영",
    "party": "더불어민주당",
    "constituency": "강원 춘천시·철원군·화천군·양구군 갑",
    "is_proportional": false,
    "id": 6,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "한기호",
    "party": "국민의힘",
    "constituency": "강원 춘천시·철원군·화천군·양구군 을",
    "is_proportional": false,
    "id": 7,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "유상범",
    "party": "국민의힘",
    "constituency": "강원 홍천군·횡성군·영월군·평창군",
    "is_proportional": false,
    "id": 8,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김성회",
    "party": "더불어민주당",
    "constituency": "경기 고양시 갑",
    "is_proportional": false,
    "id": 9,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이기헌",
    "party": "더불어민주당",
    "constituency": "경기 고양시 병",
    "is_proportional": false,
    "id": 10,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "한준호",
    "party": "더불어민주당",
    "constituency": "경기 고양시 을",
    "is_proportional": false,
    "id": 11,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김영환",
    "party": "더불어민주당",
    "constituency": "경기 고양시 정",
    "is_proportional": false,
    "id": 12,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "임오경",
    "party": "더불어민주당",
    "constituency": "경기 광명시 갑",
    "is_proportional": false,
    "id": 13,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김남희",
    "party": "더불어민주당",
    "constituency": "경기 광명시 을",
    "is_proportional": false,
    "id": 14,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "소병훈",
    "party": "더불어민주당",
    "constituency": "경기 광주시 갑",
    "is_proportional": false,
    "id": 15,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "안태준",
    "party": "더불어민주당",
    "constituency": "경기 광주시 을",
    "is_proportional": false,
    "id": 16,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "윤호중",
    "party": "더불어민주당",
    "constituency": "경기 구리시",
    "is_proportional": false,
    "id": 17,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이학영",
    "party": "더불어민주당",
    "constituency": "경기 군포시",
    "is_proportional": false,
    "id": 18,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김주영",
    "party": "더불어민주당",
    "constituency": "경기 김포시 갑",
    "is_proportional": false,
    "id": 19,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박상혁",
    "party": "더불어민주당",
    "constituency": "경기 김포시 을",
    "is_proportional": false,
    "id": 20,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "최민희",
    "party": "더불어민주당",
    "constituency": "경기 남양주시 갑",
    "is_proportional": false,
    "id": 21,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김용민",
    "party": "더불어민주당",
    "constituency": "경기 남양주시 병",
    "is_proportional": false,
    "id": 22,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김병주",
    "party": "더불어민주당",
    "constituency": "경기 남양주시 을",
    "is_proportional": false,
    "id": 23,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "정성호",
    "party": "더불어민주당",
    "constituency": "경기 동두천시·양주시·연천군 갑",
    "is_proportional": false,
    "id": 24,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김성원",
    "party": "국민의힘",
    "constituency": "경기 동두천시·양주시·연천군 을",
    "is_proportional": false,
    "id": 25,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "서영석",
    "party": "더불어민주당",
    "constituency": "경기 부천시 갑",
    "is_proportional": false,
    "id": 26,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이건태",
    "party": "더불어민주당",
    "constituency": "경기 부천시 병",
    "is_proportional": false,
    "id": 27,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김기표",
    "party": "더불어민주당",
    "constituency": "경기 부천시 을",
    "is_proportional": false,
    "id": 28,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "안철수",
    "party": "국민의힘",
    "constituency": "경기 성남시 분당구 갑",
    "is_proportional": false,
    "id": 29,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김은혜",
    "party": "국민의힘",
    "constituency": "경기 성남시 분당구 을",
    "is_proportional": false,
    "id": 30,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김태년",
    "party": "더불어민주당",
    "constituency": "경기 성남시 수정구",
    "is_proportional": false,
    "id": 31,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이수진",
    "party": "더불어민주당",
    "constituency": "경기 성남시 중원구",
    "is_proportional": false,
    "id": 32,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김승원",
    "party": "더불어민주당",
    "constituency": "경기 수원시 갑",
    "is_proportional": false,
    "id": 33,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "염태영",
    "party": "더불어민주당",
    "constituency": "경기 수원시 무",
    "is_proportional": false,
    "id": 34,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김영진",
    "party": "더불어민주당",
    "constituency": "경기 수원시 병",
    "is_proportional": false,
    "id": 35,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "백혜련",
    "party": "더불어민주당",
    "constituency": "경기 수원시 을",
    "is_proportional": false,
    "id": 36,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김준혁",
    "party": "더불어민주당",
    "constituency": "경기 수원시 정",
    "is_proportional": false,
    "id": 37,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "문정복",
    "party": "더불어민주당",
    "constituency": "경기 시흥시 갑",
    "is_proportional": false,
    "id": 38,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "조정식",
    "party": "무소속",
    "constituency": "경기 시흥시 을",
    "is_proportional": false,
    "id": 39,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김남국",
    "party": "더불어민주당",
    "constituency": "경기 안산시 갑",
    "is_proportional": false,
    "id": 40,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박해철",
    "party": "더불어민주당",
    "constituency": "경기 안산시 병",
    "is_proportional": false,
    "id": 41,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김현",
    "party": "더불어민주당",
    "constituency": "경기 안산시 을",
    "is_proportional": false,
    "id": 42,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "윤종군",
    "party": "더불어민주당",
    "constituency": "경기 안성시",
    "is_proportional": false,
    "id": 43,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "민병덕",
    "party": "더불어민주당",
    "constituency": "경기 안양시 동안구 갑",
    "is_proportional": false,
    "id": 44,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이재정",
    "party": "더불어민주당",
    "constituency": "경기 안양시 동안구 을",
    "is_proportional": false,
    "id": 45,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "강득구",
    "party": "더불어민주당",
    "constituency": "경기 안양시 만안구",
    "is_proportional": false,
    "id": 46,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김선교",
    "party": "국민의힘",
    "constituency": "경기 여주시·양평군",
    "is_proportional": false,
    "id": 47,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "차지호",
    "party": "더불어민주당",
    "constituency": "경기 오산시",
    "is_proportional": false,
    "id": 48,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이상식",
    "party": "더불어민주당",
    "constituency": "경기 용인시 갑",
    "is_proportional": false,
    "id": 49,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "부승찬",
    "party": "더불어민주당",
    "constituency": "경기 용인시 병",
    "is_proportional": false,
    "id": 50,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "손명수",
    "party": "더불어민주당",
    "constituency": "경기 용인시 을",
    "is_proportional": false,
    "id": 51,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이언주",
    "party": "더불어민주당",
    "constituency": "경기 용인시 정",
    "is_proportional": false,
    "id": 52,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이소영",
    "party": "더불어민주당",
    "constituency": "경기 의왕시·과천시",
    "is_proportional": false,
    "id": 53,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박지혜",
    "party": "더불어민주당",
    "constituency": "경기 의정부시 갑",
    "is_proportional": false,
    "id": 54,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이재강",
    "party": "더불어민주당",
    "constituency": "경기 의정부시 을",
    "is_proportional": false,
    "id": 55,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "송석준",
    "party": "국민의힘",
    "constituency": "경기 이천시",
    "is_proportional": false,
    "id": 56,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "윤후덕",
    "party": "더불어민주당",
    "constituency": "경기 파주시 갑",
    "is_proportional": false,
    "id": 57,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박정",
    "party": "더불어민주당",
    "constituency": "경기 파주시 을",
    "is_proportional": false,
    "id": 58,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "홍기원",
    "party": "더불어민주당",
    "constituency": "경기 평택시 갑",
    "is_proportional": false,
    "id": 59,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김현정",
    "party": "더불어민주당",
    "constituency": "경기 평택시 병",
    "is_proportional": false,
    "id": 60,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "유의동",
    "party": "국민의힘",
    "constituency": "경기 평택시 을",
    "is_proportional": false,
    "id": 61,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김용태",
    "party": "국민의힘",
    "constituency": "경기 포천시·가평군",
    "is_proportional": false,
    "id": 62,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이광재",
    "party": "더불어민주당",
    "constituency": "경기 하남시 갑",
    "is_proportional": false,
    "id": 63,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김용만",
    "party": "더불어민주당",
    "constituency": "경기 하남시 을",
    "is_proportional": false,
    "id": 64,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "송옥주",
    "party": "더불어민주당",
    "constituency": "경기 화성시 갑",
    "is_proportional": false,
    "id": 65,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "권칠승",
    "party": "더불어민주당",
    "constituency": "경기 화성시 병",
    "is_proportional": false,
    "id": 66,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이준석",
    "party": "개혁신당",
    "constituency": "경기 화성시 을",
    "is_proportional": false,
    "id": 67,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "전용기",
    "party": "더불어민주당",
    "constituency": "경기 화성시 정",
    "is_proportional": false,
    "id": 68,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "서일준",
    "party": "국민의힘",
    "constituency": "경남 거제시",
    "is_proportional": false,
    "id": 69,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "민홍철",
    "party": "더불어민주당",
    "constituency": "경남 김해시 갑",
    "is_proportional": false,
    "id": 70,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김정호",
    "party": "더불어민주당",
    "constituency": "경남 김해시 을",
    "is_proportional": false,
    "id": 71,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박상웅",
    "party": "국민의힘",
    "constituency": "경남 밀양시·의령군·함안군·창녕군",
    "is_proportional": false,
    "id": 72,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "서천호",
    "party": "국민의힘",
    "constituency": "경남 사천시·남해군·하동군",
    "is_proportional": false,
    "id": 73,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "신성범",
    "party": "국민의힘",
    "constituency": "경남 산청군·함양군·거창군·합천군",
    "is_proportional": false,
    "id": 74,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "윤영석",
    "party": "국민의힘",
    "constituency": "경남 양산시 갑",
    "is_proportional": false,
    "id": 75,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김태호",
    "party": "국민의힘",
    "constituency": "경남 양산시 을",
    "is_proportional": false,
    "id": 76,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박대출",
    "party": "국민의힘",
    "constituency": "경남 진주시 갑",
    "is_proportional": false,
    "id": 77,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "강민국",
    "party": "국민의힘",
    "constituency": "경남 진주시 을",
    "is_proportional": false,
    "id": 78,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "최형두",
    "party": "국민의힘",
    "constituency": "경남 창원시 마산합포구",
    "is_proportional": false,
    "id": 79,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "윤한홍",
    "party": "국민의힘",
    "constituency": "경남 창원시 마산회원구",
    "is_proportional": false,
    "id": 80,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "허성무",
    "party": "더불어민주당",
    "constituency": "경남 창원시 성산구",
    "is_proportional": false,
    "id": 81,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김종양",
    "party": "국민의힘",
    "constituency": "경남 창원시 의창구",
    "is_proportional": false,
    "id": 82,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이종욱",
    "party": "국민의힘",
    "constituency": "경남 창원시 진해구",
    "is_proportional": false,
    "id": 83,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "정점식",
    "party": "국민의힘",
    "constituency": "경남 통영시·고성군",
    "is_proportional": false,
    "id": 84,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "조지연",
    "party": "국민의힘",
    "constituency": "경북 경산시",
    "is_proportional": false,
    "id": 85,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김석기",
    "party": "국민의힘",
    "constituency": "경북 경주시",
    "is_proportional": false,
    "id": 86,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "정희용",
    "party": "국민의힘",
    "constituency": "경북 고령군·성주군·칠곡군",
    "is_proportional": false,
    "id": 87,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "구자근",
    "party": "국민의힘",
    "constituency": "경북 구미시 갑",
    "is_proportional": false,
    "id": 88,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "강명구",
    "party": "국민의힘",
    "constituency": "경북 구미시 을",
    "is_proportional": false,
    "id": 89,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "송언석",
    "party": "국민의힘",
    "constituency": "경북 김천시",
    "is_proportional": false,
    "id": 90,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "임이자",
    "party": "국민의힘",
    "constituency": "경북 상주시·문경시",
    "is_proportional": false,
    "id": 91,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김형동",
    "party": "국민의힘",
    "constituency": "경북 안동시·예천군",
    "is_proportional": false,
    "id": 92,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "임종득",
    "party": "국민의힘",
    "constituency": "경북 영주시·영양군·봉화군",
    "is_proportional": false,
    "id": 93,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이만희",
    "party": "국민의힘",
    "constituency": "경북 영천시·청도군",
    "is_proportional": false,
    "id": 94,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박형수",
    "party": "국민의힘",
    "constituency": "경북 의성군·청송군·영덕군·울진군",
    "is_proportional": false,
    "id": 95,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이상휘",
    "party": "국민의힘",
    "constituency": "경북 포항시 남구·울릉군",
    "is_proportional": false,
    "id": 96,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김정재",
    "party": "국민의힘",
    "constituency": "경북 포항시 북구",
    "is_proportional": false,
    "id": 97,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박균택",
    "party": "더불어민주당",
    "constituency": "광주 광산구 갑",
    "is_proportional": false,
    "id": 98,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "임문영",
    "party": "더불어민주당",
    "constituency": "광주 광산구 을",
    "is_proportional": false,
    "id": 99,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "정진욱",
    "party": "더불어민주당",
    "constituency": "광주 동구·남구 갑",
    "is_proportional": false,
    "id": 100,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "안도걸",
    "party": "더불어민주당",
    "constituency": "광주 동구·남구 을",
    "is_proportional": false,
    "id": 101,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "정준호",
    "party": "더불어민주당",
    "constituency": "광주 북구 갑",
    "is_proportional": false,
    "id": 102,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "전진숙",
    "party": "더불어민주당",
    "constituency": "광주 북구 을",
    "is_proportional": false,
    "id": 103,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "조인철",
    "party": "더불어민주당",
    "constituency": "광주 서구 갑",
    "is_proportional": false,
    "id": 104,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "양부남",
    "party": "더불어민주당",
    "constituency": "광주 서구 을",
    "is_proportional": false,
    "id": 105,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "유영하",
    "party": "국민의힘",
    "constituency": "대구 달서구 갑",
    "is_proportional": false,
    "id": 106,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "권영진",
    "party": "국민의힘",
    "constituency": "대구 달서구 병",
    "is_proportional": false,
    "id": 107,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "윤재옥",
    "party": "국민의힘",
    "constituency": "대구 달서구 을",
    "is_proportional": false,
    "id": 108,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이진숙",
    "party": "국민의힘",
    "constituency": "대구 달성군",
    "is_proportional": false,
    "id": 109,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "최은석",
    "party": "국민의힘",
    "constituency": "대구 동구·군위군 갑",
    "is_proportional": false,
    "id": 110,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "강대식",
    "party": "국민의힘",
    "constituency": "대구 동구·군위군 을",
    "is_proportional": false,
    "id": 111,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "우재준",
    "party": "국민의힘",
    "constituency": "대구 북구 갑",
    "is_proportional": false,
    "id": 112,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김승수",
    "party": "국민의힘",
    "constituency": "대구 북구 을",
    "is_proportional": false,
    "id": 113,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김상훈",
    "party": "국민의힘",
    "constituency": "대구 서구",
    "is_proportional": false,
    "id": 114,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "주호영",
    "party": "국민의힘",
    "constituency": "대구 수성구 갑",
    "is_proportional": false,
    "id": 115,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이인선",
    "party": "국민의힘",
    "constituency": "대구 수성구 을",
    "is_proportional": false,
    "id": 116,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김기웅",
    "party": "국민의힘",
    "constituency": "대구 중구·남구",
    "is_proportional": false,
    "id": 117,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박정현",
    "party": "더불어민주당",
    "constituency": "대전 대덕구",
    "is_proportional": false,
    "id": 118,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "장철민",
    "party": "더불어민주당",
    "constituency": "대전 동구",
    "is_proportional": false,
    "id": 119,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "장종태",
    "party": "더불어민주당",
    "constituency": "대전 서구 갑",
    "is_proportional": false,
    "id": 120,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박범계",
    "party": "더불어민주당",
    "constituency": "대전 서구 을",
    "is_proportional": false,
    "id": 121,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "조승래",
    "party": "더불어민주당",
    "constituency": "대전 유성구 갑",
    "is_proportional": false,
    "id": 122,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "황정아",
    "party": "더불어민주당",
    "constituency": "대전 유성구 을",
    "is_proportional": false,
    "id": 123,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박용갑",
    "party": "더불어민주당",
    "constituency": "대전 중구",
    "is_proportional": false,
    "id": 124,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김도읍",
    "party": "국민의힘",
    "constituency": "부산 강서구",
    "is_proportional": false,
    "id": 125,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "백종헌",
    "party": "국민의힘",
    "constituency": "부산 금정구",
    "is_proportional": false,
    "id": 126,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "정동만",
    "party": "국민의힘",
    "constituency": "부산 기장군",
    "is_proportional": false,
    "id": 127,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박수영",
    "party": "국민의힘",
    "constituency": "부산 남구",
    "is_proportional": false,
    "id": 128,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "서지영",
    "party": "국민의힘",
    "constituency": "부산 동래구",
    "is_proportional": false,
    "id": 129,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "정성국",
    "party": "국민의힘",
    "constituency": "부산 부산진구 갑",
    "is_proportional": false,
    "id": 130,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이헌승",
    "party": "국민의힘",
    "constituency": "부산 부산진구 을",
    "is_proportional": false,
    "id": 131,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "한동훈",
    "party": "무소속",
    "constituency": "부산 북구 갑",
    "is_proportional": false,
    "id": 132,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박성훈",
    "party": "국민의힘",
    "constituency": "부산 북구 을",
    "is_proportional": false,
    "id": 133,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김대식",
    "party": "국민의힘",
    "constituency": "부산 사상구",
    "is_proportional": false,
    "id": 134,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이성권",
    "party": "국민의힘",
    "constituency": "부산 사하구 갑",
    "is_proportional": false,
    "id": 135,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "조경태",
    "party": "국민의힘",
    "constituency": "부산 사하구 을",
    "is_proportional": false,
    "id": 136,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "곽규택",
    "party": "국민의힘",
    "constituency": "부산 서구·동구",
    "is_proportional": false,
    "id": 137,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "정연욱",
    "party": "국민의힘",
    "constituency": "부산 수영구",
    "is_proportional": false,
    "id": 138,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김희정",
    "party": "국민의힘",
    "constituency": "부산 연제구",
    "is_proportional": false,
    "id": 139,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "조승환",
    "party": "국민의힘",
    "constituency": "부산 중구·영도구",
    "is_proportional": false,
    "id": 140,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "주진우",
    "party": "국민의힘",
    "constituency": "부산 해운대구 갑",
    "is_proportional": false,
    "id": 141,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김미애",
    "party": "국민의힘",
    "constituency": "부산 해운대구 을",
    "is_proportional": false,
    "id": 142,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "서명옥",
    "party": "국민의힘",
    "constituency": "서울 강남구 갑",
    "is_proportional": false,
    "id": 143,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "고동진",
    "party": "국민의힘",
    "constituency": "서울 강남구 병",
    "is_proportional": false,
    "id": 144,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박수민",
    "party": "국민의힘",
    "constituency": "서울 강남구 을",
    "is_proportional": false,
    "id": 145,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "진선미",
    "party": "더불어민주당",
    "constituency": "서울 강동구 갑",
    "is_proportional": false,
    "id": 146,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이해식",
    "party": "더불어민주당",
    "constituency": "서울 강동구 을",
    "is_proportional": false,
    "id": 147,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "천준호",
    "party": "더불어민주당",
    "constituency": "서울 강북구 갑",
    "is_proportional": false,
    "id": 148,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "한민수",
    "party": "더불어민주당",
    "constituency": "서울 강북구 을",
    "is_proportional": false,
    "id": 149,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "강선우",
    "party": "무소속",
    "constituency": "서울 강서구 갑",
    "is_proportional": false,
    "id": 150,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "한정애",
    "party": "더불어민주당",
    "constituency": "서울 강서구 병",
    "is_proportional": false,
    "id": 151,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "진성준",
    "party": "더불어민주당",
    "constituency": "서울 강서구 을",
    "is_proportional": false,
    "id": 152,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박민규",
    "party": "더불어민주당",
    "constituency": "서울 관악구 갑",
    "is_proportional": false,
    "id": 153,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "정태호",
    "party": "더불어민주당",
    "constituency": "서울 관악구 을",
    "is_proportional": false,
    "id": 154,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이정헌",
    "party": "더불어민주당",
    "constituency": "서울 광진구 갑",
    "is_proportional": false,
    "id": 155,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "고민정",
    "party": "더불어민주당",
    "constituency": "서울 광진구 을",
    "is_proportional": false,
    "id": 156,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이인영",
    "party": "더불어민주당",
    "constituency": "서울 구로구 갑",
    "is_proportional": false,
    "id": 157,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "윤건영",
    "party": "더불어민주당",
    "constituency": "서울 구로구 을",
    "is_proportional": false,
    "id": 158,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "최기상",
    "party": "더불어민주당",
    "constituency": "서울 금천구",
    "is_proportional": false,
    "id": 159,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "우원식",
    "party": "더불어민주당",
    "constituency": "서울 노원구 갑",
    "is_proportional": false,
    "id": 160,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김성환",
    "party": "더불어민주당",
    "constituency": "서울 노원구 을",
    "is_proportional": false,
    "id": 161,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김재섭",
    "party": "국민의힘",
    "constituency": "서울 도봉구 갑",
    "is_proportional": false,
    "id": 162,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "오기형",
    "party": "더불어민주당",
    "constituency": "서울 도봉구 을",
    "is_proportional": false,
    "id": 163,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "안규백",
    "party": "더불어민주당",
    "constituency": "서울 동대문구 갑",
    "is_proportional": false,
    "id": 164,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "장경태",
    "party": "무소속",
    "constituency": "서울 동대문구 을",
    "is_proportional": false,
    "id": 165,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김병기",
    "party": "무소속",
    "constituency": "서울 동작구 갑",
    "is_proportional": false,
    "id": 166,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "나경원",
    "party": "국민의힘",
    "constituency": "서울 동작구 을",
    "is_proportional": false,
    "id": 167,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "조정훈",
    "party": "국민의힘",
    "constituency": "서울 마포구 갑",
    "is_proportional": false,
    "id": 168,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "정청래",
    "party": "더불어민주당",
    "constituency": "서울 마포구 을",
    "is_proportional": false,
    "id": 169,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김동아",
    "party": "더불어민주당",
    "constituency": "서울 서대문구 갑",
    "is_proportional": false,
    "id": 170,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김영호",
    "party": "더불어민주당",
    "constituency": "서울 서대문구 을",
    "is_proportional": false,
    "id": 171,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "조은희",
    "party": "국민의힘",
    "constituency": "서울 서초구 갑",
    "is_proportional": false,
    "id": 172,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "신동욱",
    "party": "국민의힘",
    "constituency": "서울 서초구 을",
    "is_proportional": false,
    "id": 173,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김영배",
    "party": "더불어민주당",
    "constituency": "서울 성북구 갑",
    "is_proportional": false,
    "id": 174,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김남근",
    "party": "더불어민주당",
    "constituency": "서울 성북구 을",
    "is_proportional": false,
    "id": 175,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박정훈",
    "party": "국민의힘",
    "constituency": "서울 송파구 갑",
    "is_proportional": false,
    "id": 176,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "남인순",
    "party": "더불어민주당",
    "constituency": "서울 송파구 병",
    "is_proportional": false,
    "id": 177,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "배현진",
    "party": "국민의힘",
    "constituency": "서울 송파구 을",
    "is_proportional": false,
    "id": 178,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "황희",
    "party": "더불어민주당",
    "constituency": "서울 양천구 갑",
    "is_proportional": false,
    "id": 179,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이용선",
    "party": "더불어민주당",
    "constituency": "서울 양천구 을",
    "is_proportional": false,
    "id": 180,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "채현일",
    "party": "더불어민주당",
    "constituency": "서울 영등포구 갑",
    "is_proportional": false,
    "id": 181,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김민석",
    "party": "더불어민주당",
    "constituency": "서울 영등포구 을",
    "is_proportional": false,
    "id": 182,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "권영세",
    "party": "국민의힘",
    "constituency": "서울 용산구",
    "is_proportional": false,
    "id": 183,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박주민",
    "party": "더불어민주당",
    "constituency": "서울 은평구 갑",
    "is_proportional": false,
    "id": 184,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김우영",
    "party": "더불어민주당",
    "constituency": "서울 은평구 을",
    "is_proportional": false,
    "id": 185,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "곽상언",
    "party": "더불어민주당",
    "constituency": "서울 종로구",
    "is_proportional": false,
    "id": 186,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "전현희",
    "party": "더불어민주당",
    "constituency": "서울 중구·성동구 갑",
    "is_proportional": false,
    "id": 187,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박성준",
    "party": "더불어민주당",
    "constituency": "서울 중구·성동구 을",
    "is_proportional": false,
    "id": 188,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "서영교",
    "party": "더불어민주당",
    "constituency": "서울 중랑구 갑",
    "is_proportional": false,
    "id": 189,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박홍근",
    "party": "더불어민주당",
    "constituency": "서울 중랑구 을",
    "is_proportional": false,
    "id": 190,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김종민",
    "party": "무소속",
    "constituency": "세종 갑",
    "is_proportional": false,
    "id": 191,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "강준현",
    "party": "더불어민주당",
    "constituency": "세종 을",
    "is_proportional": false,
    "id": 192,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김태규",
    "party": "국민의힘",
    "constituency": "울산 남구 갑",
    "is_proportional": false,
    "id": 193,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김기현",
    "party": "국민의힘",
    "constituency": "울산 남구 을",
    "is_proportional": false,
    "id": 194,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김태선",
    "party": "더불어민주당",
    "constituency": "울산 동구",
    "is_proportional": false,
    "id": 195,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "윤종오",
    "party": "진보당",
    "constituency": "울산 북구",
    "is_proportional": false,
    "id": 196,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "서범수",
    "party": "국민의힘",
    "constituency": "울산 울주군",
    "is_proportional": false,
    "id": 197,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박성민",
    "party": "국민의힘",
    "constituency": "울산 중구",
    "is_proportional": false,
    "id": 198,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "유동수",
    "party": "더불어민주당",
    "constituency": "인천 계양구 갑",
    "is_proportional": false,
    "id": 199,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김남준",
    "party": "더불어민주당",
    "constituency": "인천 계양구 을",
    "is_proportional": false,
    "id": 200,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "맹성규",
    "party": "더불어민주당",
    "constituency": "인천 남동구 갑",
    "is_proportional": false,
    "id": 201,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이훈기",
    "party": "더불어민주당",
    "constituency": "인천 남동구 을",
    "is_proportional": false,
    "id": 202,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "허종식",
    "party": "더불어민주당",
    "constituency": "인천 동구·미추홀구 갑",
    "is_proportional": false,
    "id": 203,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "윤상현",
    "party": "국민의힘",
    "constituency": "인천 동구·미추홀구 을",
    "is_proportional": false,
    "id": 204,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "노종면",
    "party": "더불어민주당",
    "constituency": "인천 부평구 갑",
    "is_proportional": false,
    "id": 205,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박선원",
    "party": "더불어민주당",
    "constituency": "인천 부평구 을",
    "is_proportional": false,
    "id": 206,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김교흥",
    "party": "더불어민주당",
    "constituency": "인천 서구 갑",
    "is_proportional": false,
    "id": 207,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "모경종",
    "party": "더불어민주당",
    "constituency": "인천 서구 병",
    "is_proportional": false,
    "id": 208,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이용우",
    "party": "더불어민주당",
    "constituency": "인천 서구 을",
    "is_proportional": false,
    "id": 209,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "송영길",
    "party": "더불어민주당",
    "constituency": "인천 연수구 갑",
    "is_proportional": false,
    "id": 210,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "정일영",
    "party": "더불어민주당",
    "constituency": "인천 연수구 을",
    "is_proportional": false,
    "id": 211,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "배준영",
    "party": "국민의힘",
    "constituency": "인천 중구·강화군·옹진군",
    "is_proportional": false,
    "id": 212,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "문금주",
    "party": "더불어민주당",
    "constituency": "전남 고흥군·보성군·장흥군·강진군",
    "is_proportional": false,
    "id": 213,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "신정훈",
    "party": "더불어민주당",
    "constituency": "전남 나주시·화순군",
    "is_proportional": false,
    "id": 214,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이개호",
    "party": "더불어민주당",
    "constituency": "전남 담양군·함평군·영광군·장성군",
    "is_proportional": false,
    "id": 215,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김원이",
    "party": "더불어민주당",
    "constituency": "전남 목포시",
    "is_proportional": false,
    "id": 216,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김문수",
    "party": "더불어민주당",
    "constituency": "전남 순천시·광양시·곡성군·구례군 갑",
    "is_proportional": false,
    "id": 217,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "권향엽",
    "party": "더불어민주당",
    "constituency": "전남 순천시·광양시·곡성군·구례군 을",
    "is_proportional": false,
    "id": 218,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "주철현",
    "party": "더불어민주당",
    "constituency": "전남 여수시 갑",
    "is_proportional": false,
    "id": 219,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "조계원",
    "party": "더불어민주당",
    "constituency": "전남 여수시 을",
    "is_proportional": false,
    "id": 220,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "서삼석",
    "party": "더불어민주당",
    "constituency": "전남 영암군·무안군·신안군",
    "is_proportional": false,
    "id": 221,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박지원",
    "party": "더불어민주당",
    "constituency": "전남 해남군·완도군·진도군",
    "is_proportional": false,
    "id": 222,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김의겸",
    "party": "더불어민주당",
    "constituency": "전북 군산시·김제시·부안군 갑",
    "is_proportional": false,
    "id": 223,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박지원",
    "party": "더불어민주당",
    "constituency": "전북 군산시·김제시·부안군 을",
    "is_proportional": false,
    "id": 224,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박희승",
    "party": "더불어민주당",
    "constituency": "전북 남원시·장수군·임실군·순창군",
    "is_proportional": false,
    "id": 225,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "안호영",
    "party": "더불어민주당",
    "constituency": "전북 완주군·진안군·무주군",
    "is_proportional": false,
    "id": 226,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이춘석",
    "party": "무소속",
    "constituency": "전북 익산시 갑",
    "is_proportional": false,
    "id": 227,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "한병도",
    "party": "더불어민주당",
    "constituency": "전북 익산시 을",
    "is_proportional": false,
    "id": 228,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김윤덕",
    "party": "더불어민주당",
    "constituency": "전북 전주시 갑",
    "is_proportional": false,
    "id": 229,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "정동영",
    "party": "더불어민주당",
    "constituency": "전북 전주시 병",
    "is_proportional": false,
    "id": 230,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이성윤",
    "party": "더불어민주당",
    "constituency": "전북 전주시 을",
    "is_proportional": false,
    "id": 231,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "윤준병",
    "party": "더불어민주당",
    "constituency": "전북 정읍시·고창군",
    "is_proportional": false,
    "id": 232,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김성범",
    "party": "더불어민주당",
    "constituency": "제주 서귀포시",
    "is_proportional": false,
    "id": 233,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "문대림",
    "party": "더불어민주당",
    "constituency": "제주 제주시 갑",
    "is_proportional": false,
    "id": 234,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김한규",
    "party": "더불어민주당",
    "constituency": "제주 제주시 을",
    "is_proportional": false,
    "id": 235,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박수현",
    "party": "국민의힘",
    "constituency": "충남 공주시·부여군·청양군",
    "is_proportional": false,
    "id": 236,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "황명선",
    "party": "더불어민주당",
    "constituency": "충남 논산시·계룡시·금산군",
    "is_proportional": false,
    "id": 237,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "어기구",
    "party": "더불어민주당",
    "constituency": "충남 당진시",
    "is_proportional": false,
    "id": 238,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "장동혁",
    "party": "국민의힘",
    "constituency": "충남 보령시·서천군",
    "is_proportional": false,
    "id": 239,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "성일종",
    "party": "국민의힘",
    "constituency": "충남 서산시·태안군",
    "is_proportional": false,
    "id": 240,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "복기왕",
    "party": "더불어민주당",
    "constituency": "충남 아산시 갑",
    "is_proportional": false,
    "id": 241,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "전은수",
    "party": "더불어민주당",
    "constituency": "충남 아산시 을",
    "is_proportional": false,
    "id": 242,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "문진석",
    "party": "더불어민주당",
    "constituency": "충남 천안시 갑",
    "is_proportional": false,
    "id": 243,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이정문",
    "party": "더불어민주당",
    "constituency": "충남 천안시 병",
    "is_proportional": false,
    "id": 244,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이재관",
    "party": "더불어민주당",
    "constituency": "충남 천안시 을",
    "is_proportional": false,
    "id": 245,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "강승규",
    "party": "국민의힘",
    "constituency": "충남 홍성군·예산군",
    "is_proportional": false,
    "id": 246,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박덕흠",
    "party": "국민의힘",
    "constituency": "충북 보은군·옥천군·영동군·괴산군",
    "is_proportional": false,
    "id": 247,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "엄태영",
    "party": "국민의힘",
    "constituency": "충북 제천시·단양군",
    "is_proportional": false,
    "id": 248,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "임호선",
    "party": "더불어민주당",
    "constituency": "충북 증평군·진천군·음성군",
    "is_proportional": false,
    "id": 249,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이강일",
    "party": "더불어민주당",
    "constituency": "충북 청주시 상당구",
    "is_proportional": false,
    "id": 250,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이광희",
    "party": "더불어민주당",
    "constituency": "충북 청주시 서원구",
    "is_proportional": false,
    "id": 251,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "송재봉",
    "party": "더불어민주당",
    "constituency": "충북 청주시 청원구",
    "is_proportional": false,
    "id": 252,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이연희",
    "party": "더불어민주당",
    "constituency": "충북 청주시 흥덕구",
    "is_proportional": false,
    "id": 253,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이종배",
    "party": "국민의힘",
    "constituency": "충북 충주시",
    "is_proportional": false,
    "id": 254,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "강경숙",
    "party": "조국혁신당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 255,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "강선영",
    "party": "국민의힘",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 256,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김건",
    "party": "국민의힘",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 257,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김민전",
    "party": "국민의힘",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 258,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김선민",
    "party": "조국혁신당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 259,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김소희",
    "party": "국민의힘",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 260,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김예지",
    "party": "국민의힘",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 261,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김위상",
    "party": "국민의힘",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 262,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김윤",
    "party": "더불어민주당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 263,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김장겸",
    "party": "국민의힘",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 264,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김재원",
    "party": "조국혁신당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 265,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김준형",
    "party": "조국혁신당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 266,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "김준환",
    "party": "더불어민주당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 267,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박은정",
    "party": "조국혁신당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 268,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박준태",
    "party": "국민의힘",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 269,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박충권",
    "party": "국민의힘",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 270,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "박홍배",
    "party": "더불어민주당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 271,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "백선희",
    "party": "조국혁신당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 272,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "백승아",
    "party": "더불어민주당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 273,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "서미화",
    "party": "더불어민주당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 274,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "서왕진",
    "party": "조국혁신당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 275,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "손솔",
    "party": "진보당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 276,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "신장식",
    "party": "조국혁신당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 277,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "안상훈",
    "party": "국민의힘",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 278,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "오세희",
    "party": "더불어민주당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 279,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "용혜인",
    "party": "기본소득당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 280,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "유용원",
    "party": "국민의힘",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 281,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이달희",
    "party": "국민의힘",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 282,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이소희",
    "party": "국민의힘",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 283,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이주영",
    "party": "개혁신당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 284,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이주희",
    "party": "더불어민주당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 285,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "이해민",
    "party": "조국혁신당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 286,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "임미애",
    "party": "더불어민주당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 287,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "전종덕",
    "party": "진보당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 288,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "정춘생",
    "party": "조국혁신당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 289,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "정혜경",
    "party": "진보당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 290,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "조배숙",
    "party": "국민의힘",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 291,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "진종오",
    "party": "국민의힘",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 292,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "차규근",
    "party": "조국혁신당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 293,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "천하람",
    "party": "개혁신당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 294,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "최보윤",
    "party": "국민의힘",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 295,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "최수진",
    "party": "국민의힘",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 296,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "최혁진",
    "party": "무소속",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 297,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "한지아",
    "party": "국민의힘",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 298,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "한창민",
    "party": "사회민주당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 299,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  },
  {
    "name": "황운하",
    "party": "조국혁신당",
    "constituency": "비례대표",
    "is_proportional": true,
    "id": 300,
    "crimes_count": null,
    "crimes": [],
    "crime_status": "unverified",
    "data_note": "전과 정보는 선관위 후보자 공시자료와 별도 대조 전입니다."
  }
];

export default assemblyMembers;
